name: Deploy to GitHub Pages
on:
  schedule:
    # Min, Hr, Day, Mon, WkDay
    # Every saturday (day 6) at 6:06
    - cron: "6 6 * * 6"   
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  deploy:
    uses: "getpelican/pelican/.github/workflows/github_pages.yml@b86383fb28a160eeaf3e13cbf99469a0ed4cfcb2"
    permissions:
      contents: "read"
      pages: "write"
      id-token: "write"
    with:
      requirements: "-r requirements.txt"
      settings: "publishconf.py"
